apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - serviceaccount.yaml
  - postgres-secret.yaml
  - postgres-pvc.yaml
  - postgres-deployment.yaml
  - postgres-service.yaml
  - configmap.yaml
  - deployment.yaml
  - service.yaml
  - management-deployment.yaml
  - management-service.yaml
  - referencegrant.yaml
  - route.yaml
