apiVersion: v1
kind: Secret
metadata:
  name: dil-connector-postgres
  namespace: dil-connector
type: Opaque
stringData:
  POSTGRES_DB: connector
  POSTGRES_USER: connector
  POSTGRES_PASSWORD: connector
