apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: dil-connector-postgres-data
  namespace: dil-connector
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
